### PR TITLE
Added Arrr - extenshion for refactoring components

### PR DESCRIPTION
**Pull request by obenjiro**
Created a VS plugin for automatic components refactoring. Will be happy if you find it useful.

Video of tool in action:
https://twitter.com/obenjiro/status/1295542114261114880

### CODE REVIEW

**Comment by obenjiro** [comment]
@doggy8088 is there anything I can help to speed up review?

**Comment by doggy8088** [comment]
@obenjiro I'm testing your extension. It looks very nice! I'll speed up review. Thanks for your contribution!

**Comment by doggy8088** [comment]
@obenjiro I found two bugs in your extension and reported here: https://github.com/obenjiro/vscode-arrr/issues/9 & https://github.com/obenjiro/vscode-arrr/issues/10

**Comment by obenjiro** [comment]
Thanks a lot for bug-report! Should be fixed in v0.1.3

**Comment by doggy8088** [comment]
@obenjiro Hi, your extension will be included in [Angular Extension Pack v9.3.0](https://marketplace.visualstudio.com/items?itemName=doggy8088.angular-extension-pack).

**Pull request closed without merging**
